version: "3.5"
services:
  producer-service:
    container_name: producer-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-producer-spring-boot:latest
    ports:
      - 8090:8090
    networks:
      - spring-cloud-network
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
networks:
  spring-cloud-network:
    driver: bridge
  nats:
    name: nats